title: "Zainul's Tech Blog"
tagline: "Observations on tech in the wild"
email: hello@zainul.me
description: >- 
  Real-life tech observations. I spot things in the wild: badly designed
  interfaces, clever implementations, and systems that work better. Then
  expand on them here.
url: "https://blog.zainul.me"
github_username: zainul1996
author: "Zainul"

# Theme
theme: minima

header_pages:
  - about.md

# Build settings
timezone: Asia/Singapore
markdown: kramdown
permalink: /:year/:month/:title/
future: true

# Show excerpts on the home page
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social
twitter:
  username: zainulcain
  card: summary_large_image